### ISSUE TITLE
stim300 CRC error

### ISSUE THREAD

**Issue by Leon1128** [nearlab/stim300_rosDriver#1]
Hi!
Thanks a lot for your work!
I try to roslaunch the program with my STIM300. But I get the error：

[ WARN] [1575106728.501836908]: stim300 CRC error

How can i solve it？
Thank you.

**Comment by jamesbellaero** [comment]
We actually adapted this from some University of California school's repo. I'll look into it, but I'm not longer at UT Austin and don't have access to the stim300 anymore.

What sort of OS are you using?

**Comment by jamesbellaero** [comment]
@Leon1128 It appears that you should be using driver revision G. If you already are, then go ahead and put some outputs before line 140 of Stim300RevG.cpp and recompile. Hopefully that can help you debug what's happening.

**Comment by Leon1128** [comment]
Thank you very much. I found the cause of the error. The default datagram format in the program is RATE_ACC_INCL_TEMP_AUX. But it doesn't match my IMU settings. I modified it in service mode.Then the error was corrected.
